### ISSUE TITLE
Not working on radare2?

### ISSUE THREAD

**Issue by radare** [Luis-Hebendanz/0pack#1]
Can you please describe what's exactly not working and which version of r2 are you using? because it works perfectly fine in here. I have downloaded the 0pack release binary (because after 1h compiling i got tired of waiting), then created a silly .fasm with just an int3, and then injected it into /bin/ls. and dcu entry0 works as expected. it breaks in the 0xcc.

**Comment by radare** [comment]
Ok, i built a hello world with the flags mentioned and i was able to reproduce the "issue". I have a local fix for this entrypoint issue.. but that is not even fixing the problem for several reasons.

* the entrypoint is being modified, so software breakpoints wont work
* relocs are binary patching from the linker, so it's already possible to execute code before the entrypoint just because of how relocs work.
* Handling address 0 is incorrect in r2 right now, but that won't help on this sample because as i said, the address 0 points to the load0 segment base address, which contains the elf header at the moment of loading
* Dropping write permission to the segment is useless because the reloc code in ld.so is also patching that
* the only way to bypass this is by using hardware breakpoints which is fine for x86-64 at least

So summarizing, fixing r2 and understanding how this packer works took me about 5min, but a proper fix requires more testing. Anyways that's a neat trick :)

Thanks!

**Comment by radare** [comment]
[0packed.zip](https://github.com/Luis-Hebendanz/0pack/files/3286832/0packed.zip)

**Comment by Qubasa** [comment]
Hello,

thanks for taking interest in this little project of mine :)

"relocs are binary patching from the linker, so it's already possible to execute code before the entrypoint just because of how relocs work." 
What do you mean by that? Relocs can ony write to the memory space of the spawned process. They can not execute arbitrary op codes. 

"Dropping write permission to the segment is useless because the reloc code in ld.so is also patching that"
That is not true, if you don't add write permissions to the first load segment the relocs will generate a sigsev in the loader. I did already try that. 

"Handling address 0 is incorrect in r2 right now, but that won't help on this sample because as i said, the address 0 points to the load0 segment base address, which contains the elf header at the moment of loading"
Yeah, but I don't see the problem at setting the entry0 label to the header as supposed to the main function?
